sudo: false
env:
  - CXX=g++-4.8
language: node_js
services: mongodb
node_js:
  - "4.1"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y gcc-4.8
  - sudo apt-get install -y g++-4.8
